# Generated by Django 4.2.1 on 2023-05-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_remove_employee_company_company_employees_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employees'},
        ),
    ]
