# Generated by Django 4.2.1 on 2023-05-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_remove_employee_company_company_employees_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='type',
            new_name='asset_type',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='asset',
            new_name='asset_type',
        ),
        migrations.AlterField(
            model_name='delegatedevice',
            name='delegation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
